### ISSUE TITLE
[Bug] Error in Enable for 'Item Hotkeys'

### ISSUE THREAD

**Issue by Crystalenya** [Caraxi/SimpleTweaksPlugin#383]
Every time I try to enable/checkmark the 'Item Hotkeys' in Tooltip Tweaks , it disables itself and gives me the following error.

Error caught  in Item Hotkeys:
Error in Enable for 'Item Hotkeys'
System.NullReferenceException: Object reference not set to an instance of an object.

   at SimpleTweaksPlugin.Tweaks.Tooltips.Hotkeys.ItemHotkey.Enable(Boolean from TweakEnable) in C:\ffxiv\repo\SimpleTweaksPlugin\Tweaks\Tooltips\Hotkeys\ItemHotkey.cs:line 55
   
   at SimpleTweaksPlugin.Tweaks.Tooltips.ItemHotkeys.Enable() in C:\ffxiv\repo\SimpleTweaksPlugin\Tweaks\Tooltips\ItemHotkeys.cs:line 276
   
   at SimpleTweaksPlugin.SimpleTweaksPluginConfig.DrawTweakConfig(BaseTweak t, Boolean& hasChange) in C:\ffxiv\repo\SimpleTweaksPlugin\SimpleTweaksPluginConfig.cs:line 86
   
-------------------------------------------------------------------------------------------------------

That's a picture of the error as well: https://i.imgur.com/s1Bt69c.png

**Comment by Raxnom** [comment]
Having the same problem, after disabling stuff.

> 2022-09-21 18:21:09.404 +03:00 [ERR] [SimpleTweaksPlugin] Exception in 'Item Hotkeys' @ 'Tooltip Tweaks': Error in Enable for 'Item Hotkeys' @ 'Tooltip Tweaks'
2022-09-21 18:21:09.407 +03:00 [ERR] [SimpleTweaksPlugin] System.NullReferenceException: Object reference not set to an instance of an object.
2022-09-21 18:21:09.407 +03:00 [ERR] [SimpleTweaksPlugin]    at SimpleTweaksPlugin.Tweaks.Tooltips.Hotkeys.ItemHotkey.Enable(Boolean fromTweakEnable) in C:\ffxiv\repo\SimpleTweaksPlugin\Tweaks\Tooltips\Hotkeys\ItemHotkey.cs:line 55
2022-09-21 18:21:09.407 +03:00 [ERR] [SimpleTweaksPlugin]    at SimpleTweaksPlugin.Tweaks.Tooltips.ItemHotkeys.Enable() in C:\ffxiv\repo\SimpleTweaksPlugin\Tweaks\Tooltips\ItemHotkeys.cs:line 276
2022-09-21 18:21:09.407 +03:00 [ERR] [SimpleTweaksPlugin]    at SimpleTweaksPlugin.TweakSystem.SubTweakManager`1.Enable() in C:\ffxiv\repo\SimpleTweaksPlugin\TweakSystem\SubTweakManager.cs:line 68

screenshot - https://i.imgur.com/Tixpmee.png

**Comment by Caraxi** [comment]
May or may not be fixed in next version

**Comment by Raxnom** [comment]
Latest update fixed it for me. 

Thank you!
