### ISSUE TITLE
(NET5) Clickable URLs in chat fail

### ISSUE THREAD

**Issue by daemitus** [Caraxi/SimpleTweaksPlugin#55]
Using Process to spawn the browser with a URL needs some additional processinfo to work in net5. 
```
# From the plugin installer
_ = Process.Start(new ProcessStartInfo()
                        {
                            FileName = repoUrl,
                            UseShellExecute = true,
                        });
```

```
2021-07-11 21:05:32.134 -04:00 [ERR] Exception on InteractableLinkClicked hook
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at SimpleTweaksPlugin.Tweaks.Chat.ClickableLinks.UrlLinkHandle(UInt32 id, SeString message) in D:\a\SimpleTweaksPlugin\SimpleTweaksPlugin\Tweaks\Chat\ClickableLinks.cs:line 21
   at Dalamud.Game.Internal.Gui.ChatGui.InteractableLinkClickedDetour(IntPtr managerPtr, IntPtr messagePtr) in C:\Users\Raymond\code\Dalamud\Dalamud\Game\Internal\Gui\ChatGui.cs:line 468
```

**Comment by daemitus** [comment]
Assuming you are using Process to goto the URL anyways. I didn't look.
