### ISSUE TITLE
Game Crash when opening loot window

### ISSUE THREAD

**Issue by Grimlock21** [Caraxi/SimpleTweaksPlugin#881]
Completed EX3; crashed 3 times trying to open the chest and roll on loot. Had tweak "Enhanced Loot Window" enabled.

**Comment by byte-warlock** [comment]
Think I encountered this too, in Tower of Babil after the second boss. Stack trace:
```
Unhandled native exception occurred at ffxiv_dx11.exe+80B3D8
Code: C0000005
Dump error: MiniDumpWriteDump(0x474, 31692, 0xe4(C:\Users\redacted\AppData\Roaming\XIVLauncher\dalamud_appcrash_20241116_154452_542_31692.dmp), MiniDumpWithFullMemory, ..., nullptr, nullptr) error: 0x1
System Time: 2024-11-16 15:44:52.5677229
   at SimpleTweaksPlugin.Tweaks.UiAdjustment.LootWindowDuplicateUniqueItemIndicator.<>c__DisplayClass16_0.<PlayerHasItem>b__0(InventoryType inventory)

   at System.Linq.Enumerable.Sum[TSource,TResult,TAccumulator](IEnumerable`1 source, Func`2 selector)

   at SimpleTweaksPlugin.Tweaks.UiAdjustment.LootWindowDuplicateUniqueItemIndicator.PlayerHasItem(UInt32 itemId)

   at SimpleTweaksPlugin.Tweaks.UiAdjustment.LootWindowDuplicateUniqueItemIndicator.OnNeedGreedRequestedUpdate(AddonNeedGreed* callingAddon)

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)

   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at SimpleTweaksPlugin.Events.EventController.EventSubscriber.Invoke(Object args)

   at SimpleTweaksPlugin.Events.EventController.HandleEvent(AddonEvent type, AddonArgs args)

   at Dalamud.Game.Addon.Lifecycle.AddonLifecycle.InvokeListenersSafely(AddonEvent eventType, AddonArgs args, String blame)

   at Dalamud.Game.Addon.Lifecycle.AddonLifecycle.OnRequestedUpdate(AtkUnitBase* addon, NumberArrayData** numberArrayData, StringArrayData** stringArrayData)

   at Dalamud.Game.Framework.HandleFrameworkUpdate(Framework* thisPtr)
```

**Comment by Aireil** [comment]
Should be fixed if you restart your game.

**Comment by dalamudx** [comment]
+1
not work after restart game,so i just disabled all option about loot
